# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proizvod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategorija', models.CharField(choices=[('kapije', 'kapije'), ('ograde', 'ograde'), ('gelenderi', 'gelenderi'), ('ogradice za terase', 'ogradice za terase'), ('galanterija', 'galanterija')], default='kapije', max_length=60, verbose_name='kategorija')),
                ('materijal', models.CharField(choices=[('prohrom-inox', 'prohrom-inox'), ('crni čelik-kovano gvožđe', 'crni čelik-kovano gvožđe')], default='prohrom-inox', max_length=60, verbose_name='materijal')),
                ('naziv', models.CharField(max_length=50)),
                ('opis', models.TextField()),
                ('cena', models.IntegerField()),
            ],
        ),
    ]
