# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20170517_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='artikal',
            name='category',
            field=models.CharField(choices=[('kapije', 'kapije'), ('ograde', 'ograde'), ('gelenderi', 'gelenderi'), ('ogradice za terase', 'ogradice za terase'), ('galanterija', 'galanterija')], default='kapije', max_length=60, verbose_name='kategorija'),
        ),
        migrations.AddField(
            model_name='artikal',
            name='mat',
            field=models.CharField(choices=[('prohrom-inox', 'prohrom-inox'), ('crni čelik-kovano gvožđe', 'crni čelik-kovano gvožđe')], default='prohrom-inox', max_length=60, verbose_name='materijal'),
        ),
    ]
