# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20170517_1156'),
    ]

    operations = [
        migrations.CreateModel(
            name='Naslov',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Artikal',
        ),
    ]
