# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 11:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20170517_1258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proizvod',
            name='cena',
        ),
    ]
