# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-29 08:46
from __future__ import unicode_literals

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_proizvod_cena'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proizvod',
            name='naziv',
        ),
        migrations.RemoveField(
            model_name='proizvod',
            name='opis',
        ),
        migrations.AddField(
            model_name='proizvod',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='proizvod',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=products.models.upload_location, width_field='width_field'),
        ),
        migrations.AddField(
            model_name='proizvod',
            name='width_field',
            field=models.IntegerField(default=0),
        ),
    ]
